version: '2'
services:
  mysqldb:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
    #  - db_data:/var/lib/mysql
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: konbini
      MYSQL_USER: konbini
      MYSQL_PASSWORD: konbini
  api:
    build: .
    image: test-assignment
    command: nodemon server
    ports:
      - "3000:3000"
    environment:
      - "CORS=1"
      - "DEBUG=express:*"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysqldb
  web:
    image: test-assignment
    command: npm start --prefix react-src
    ports:
      - "4200:4200"
    environment:
      - "REACT_APP_API_URL=http://localhost:3000"
    volumes:
      - ./react-src:/usr/src/app/react-src
      - /usr/src/app/react-src/node_modules
    depends_on:
      - api
